#ifndef WIFI_ACCESS_INFO_H // guard
#define WIFI_ACCESS_INFO_H

#define WIFI_SSID     "INSERT_YOUR_WIFI_SSID_HERE"
#define WIFI_PASSWORD "INSERT_YOUR_SECRET_WIFI_WPA2_PRESHARED_SECRET_HERE"

#endif /* WIFI_ACCESS_INFO_H */
